---
- hosts: webservers
  tasks: 
  - name: deny everything and enable UFW
    ufw:
      state: enabled
      policy: deny
  - name: apt update
    apt:
      update_cache: yes
  - name: install dependencies
    apt:
      name:
        - apache2
        - php
  - name: allow OpenSSH
    ufw:
      rule: allow
      name: OpenSSH
  - name: allow Apache
    ufw:
      rule: allow
      name: Apache

  - name: check composer
    stat: path=/usr/local/bin/composer
    register: composer_bin
    tags: composer
  - block:
    - name: download composer
      get_url: 
        url: https://getcomposer.org/installer
        dest: /tmp/installer/composer-setup.php
    - name: install composer
      shell: php /tmp/installer/composer-setup.php --install-dir=/usr/local/bin
    - name: rename composer.phar to composer
      shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer
    - name: make composer executable
      file:
        path: /usr/local/bin/composer
        mode: a+x
        state: file
    when: not composer_bin.stat.exists
    tags: composer