---
- name: install dependencies
  apt:
    name: apache2

- name: allow Apache through firewall
  ufw:
    rule: allow
    name: Apache

- name: set mpm-prefork.conf
  template:
    src: ./mpm-prefork.j2
    dest: /etc/apache2/mods-available/mpm-prefork.conf