---
- name: get latest version
  git:
    repo: https://github.com/sirogane1013/submanage-core.git
    dest: /var/www/html/submanage-core

- name: composer install
  shell:
    cmd: composer install
    chdir: /var/www/html/submanage-core

- name: npm install
  npm:
    path: /var/www/html/submanage-core